// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2eVS53c4LPHM3e_Yd1sLTtyVvA63Mb4M',
    appId: '1:988658912152:web:bf6c4aa65f02886e7bf9ed',
    messagingSenderId: '988658912152',
    projectId: 'streamit-5ef16',
    authDomain: 'streamit-5ef16.firebaseapp.com',
    databaseURL: 'https://streamit-5ef16-default-rtdb.firebaseio.com',
    storageBucket: 'streamit-5ef16.firebasestorage.app',
    measurementId: 'G-YEC2R15CR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsJLRihuO-i2cMfJeB7lLeCJ158e8yeFk',
    appId: '1:988658912152:android:b003f97916b3e6667bf9ed',
    messagingSenderId: '988658912152',
    projectId: 'streamit-5ef16',
    databaseURL: 'https://streamit-5ef16-default-rtdb.firebaseio.com',
    storageBucket: 'streamit-5ef16.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALJRlUFbCsnlE_u6jBiSebNgeq86V4gps',
    appId: '1:988658912152:ios:bc8499ae522fa3357bf9ed',
    messagingSenderId: '988658912152',
    projectId: 'streamit-5ef16',
    databaseURL: 'https://streamit-5ef16-default-rtdb.firebaseio.com',
    storageBucket: 'streamit-5ef16.firebasestorage.app',
    androidClientId: '988658912152-78q6biuf9lklfb4tmju9f303bn0cdm4i.apps.googleusercontent.com',
    iosClientId: '988658912152-umbjicbirfpkdh6stjdnvr2vn5pjtmk2.apps.googleusercontent.com',
    iosBundleId: 'com.moviestream.ios',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALJRlUFbCsnlE_u6jBiSebNgeq86V4gps',
    appId: '1:988658912152:ios:4b9c500c230b36e27bf9ed',
    messagingSenderId: '988658912152',
    projectId: 'streamit-5ef16',
    databaseURL: 'https://streamit-5ef16-default-rtdb.firebaseio.com',
    storageBucket: 'streamit-5ef16.firebasestorage.app',
    androidClientId: '988658912152-78q6biuf9lklfb4tmju9f303bn0cdm4i.apps.googleusercontent.com',
    iosClientId: '988658912152-muce2ope94qvtneaubdetmqgsr4me2gp.apps.googleusercontent.com',
    iosBundleId: 'com.moviestream.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2eVS53c4LPHM3e_Yd1sLTtyVvA63Mb4M',
    appId: '1:988658912152:web:57e56ab96f10cff17bf9ed',
    messagingSenderId: '988658912152',
    projectId: 'streamit-5ef16',
    authDomain: 'streamit-5ef16.firebaseapp.com',
    databaseURL: 'https://streamit-5ef16-default-rtdb.firebaseio.com',
    storageBucket: 'streamit-5ef16.firebasestorage.app',
    measurementId: 'G-84B5NC2BPQ',
  );
}
