// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDevY_5B7lJZkFyiC6rZrqp2vwEzZm4tYE',
    appId: '1:303674087931:web:7b31081bd2e4ae7677135e',
    messagingSenderId: '303674087931',
    projectId: 'dtlive-541ce',
    authDomain: 'dtlive-541ce.firebaseapp.com',
    storageBucket: 'dtlive-541ce.firebasestorage.app',
    measurementId: 'G-RLXQYVNQ4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo8L9r73VZsjOJreG2WsbgNfa5-0a5tCk',
    appId: '1:303674087931:android:c367f9056d9e081f77135e',
    messagingSenderId: '303674087931',
    projectId: 'dtlive-541ce',
    storageBucket: 'dtlive-541ce.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu9UTjhR94VC6haAo3WDAqbRv7Fs4dRjk',
    appId: '1:303674087931:ios:a2469ee73a50722677135e',
    messagingSenderId: '303674087931',
    projectId: 'dtlive-541ce',
    storageBucket: 'dtlive-541ce.firebasestorage.app',
    iosBundleId: 'com.moviestream.ios',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu9UTjhR94VC6haAo3WDAqbRv7Fs4dRjk',
    appId: '1:303674087931:ios:53432d9163323f4277135e',
    messagingSenderId: '303674087931',
    projectId: 'dtlive-541ce',
    storageBucket: 'dtlive-541ce.firebasestorage.app',
    iosBundleId: 'com.moviestream.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDevY_5B7lJZkFyiC6rZrqp2vwEzZm4tYE',
    appId: '1:303674087931:web:d4951b257afbce5277135e',
    messagingSenderId: '303674087931',
    projectId: 'dtlive-541ce',
    authDomain: 'dtlive-541ce.firebaseapp.com',
    storageBucket: 'dtlive-541ce.firebasestorage.app',
    measurementId: 'G-JFQNLWYWHL',
  );
}
