// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH7SLoHkaSkvn8PSFbfi4P_zYUZjsZQvQ',
    appId: '1:773450355985:web:27537a2b6ca4ea600ce8b0',
    messagingSenderId: '773450355985',
    projectId: 'streamit-7bbe3',
    authDomain: 'streamit-7bbe3.firebaseapp.com',
    databaseURL: 'https://streamit-7bbe3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'streamit-7bbe3.firebasestorage.app',
    measurementId: 'G-0VPRVT2DZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZbpBqkGZELqnNWHle9XoZ_ov2h3lIuMw',
    appId: '1:773450355985:android:7f13282f6a49f2b70ce8b0',
    messagingSenderId: '773450355985',
    projectId: 'streamit-7bbe3',
    databaseURL: 'https://streamit-7bbe3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'streamit-7bbe3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHO79el1qE7mbbQvZgPN3l5GvIvTtV1HM',
    appId: '1:773450355985:ios:6e69ed5c00bf25560ce8b0',
    messagingSenderId: '773450355985',
    projectId: 'streamit-7bbe3',
    databaseURL: 'https://streamit-7bbe3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'streamit-7bbe3.firebasestorage.app',
    androidClientId: '773450355985-k4ubpgfjuv6hqtjhvh3q9vp0a68s9bnc.apps.googleusercontent.com',
    iosClientId: '773450355985-ugs4bq465uk32og0cf9q1ne17klsafh7.apps.googleusercontent.com',
    iosBundleId: 'com.moviestream.ios',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHO79el1qE7mbbQvZgPN3l5GvIvTtV1HM',
    appId: '1:773450355985:ios:148509fdcf6cb0ad0ce8b0',
    messagingSenderId: '773450355985',
    projectId: 'streamit-7bbe3',
    databaseURL: 'https://streamit-7bbe3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'streamit-7bbe3.firebasestorage.app',
    androidClientId: '773450355985-k4ubpgfjuv6hqtjhvh3q9vp0a68s9bnc.apps.googleusercontent.com',
    iosClientId: '773450355985-edufn5qs1u2jr7aqjrhascmr5rjtvrs3.apps.googleusercontent.com',
    iosBundleId: 'com.moviestream.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH7SLoHkaSkvn8PSFbfi4P_zYUZjsZQvQ',
    appId: '1:773450355985:web:2547832d95b58daa0ce8b0',
    messagingSenderId: '773450355985',
    projectId: 'streamit-7bbe3',
    authDomain: 'streamit-7bbe3.firebaseapp.com',
    databaseURL: 'https://streamit-7bbe3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'streamit-7bbe3.firebasestorage.app',
    measurementId: 'G-8BQ704ENCX',
  );
}
